version: '3.8'

volumes:
  db:

services:
  db:
    image: mariadb:11.3-rc
    container_name: db
    restart: always
    env_file:
      - .envs/db.env
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
