# Generated by Django 5.0 on 2023-12-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('category', models.CharField(choices=[('F', 'Fixed'), ('G', 'Goal'), ('I', 'Investment'), ('K', 'Knowledge'), ('P', 'Pleasures')], max_length=1, primary_key=True, serialize=False)),
                ('percentage', models.IntegerField(default=20)),
            ],
        ),
    ]
