# Generated by Django 5.0 on 2023-12-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Wage'), (2, 'Advance'), (3, 'Dividend'), (4, 'Other')], max_length=1)),
            ],
        ),
    ]
