# Generated by Django 5.0 on 2023-12-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='value',
            field=models.FloatField(),
        ),
    ]
